# Generated by Django 5.0.7 on 2026-07-11 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='label',
        ),
        migrations.AddField(
            model_name='polygon',
            name='shape_type',
            field=models.CharField(choices=[('polygon', 'Polygon'), ('box', 'Box')], default='polygon', max_length=10),
        ),
        migrations.CreateModel(
            name='AnnotationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#5B8DEF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='polygon',
            name='annotation_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polygons', to='annotations.annotationclass'),
        ),
        migrations.AddConstraint(
            model_name='annotationclass',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_class_name_per_owner'),
        ),
    ]
